spring:
  application:
    name: subscription
  devtools:
    add-properties: false

  datasource:
    url: jdbc:mysql://localhost:3306/subscriptiondb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root            # ðŸ”¹ use your MySQL username
    password: Ranad@06uS1cS7&e          # ðŸ”¹ use your MySQL password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update        # âœ… auto-creates table if not exist
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8081

management:
  tracing:
    enabled: false             # ðŸš« Disable Zipkin & tracing completely
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus, env, beans, loggers
  endpoint:
    health:
      show-details: always

logging:
  pattern:
    level: "%5p [${spring.application.name:},traceId=%X{traceId:-},spanId=%X{spanId:-}]"
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 10
  file:
    name: logs/subscription.log
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.practice.Subscription.convertor.EncryptionConverter: DEBUG
    com.practice.Subscription.service.SubscriptionServiceImpl: DEBUG


customer:
  service:
    url: http://localhost:8082
